version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - database
    environment:
      - REDIS_HOST=redis
      - DATABASE_HOST=database

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"

  database:
    image: postgres:14
    environment:
      POSTGRES_DB: koronet_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
