apiVersion: apps/v1
kind: Deployment
metadata:
  name: koronet-web
  labels:
    app: koronet-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: koronet-web
  template:
    metadata:
      labels:
        app: koronet-web
    spec:
      containers:
      - name: koronet-web
        image: koronet/webserver:latest # Replace with the actual image name
        ports:
        - containerPort: 5000
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: DATABASE_HOST
          value: "postgres"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
      restartPolicy: Always
