apiVersion: v1
kind: Service
metadata:
  name: koronet-web-service
  labels:
    app: koronet-web
spec:
  selector:
    app: koronet-web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer
